### ISSUE TITLE
Add a websocket client

### ISSUE THREAD

**Issue by SajayAntony** [SajayAntony/cmdport#4]

**Comment by SajayAntony** [comment]
ping!

**Comment by sivagms** [comment]
Done

**Comment by SajayAntony** [comment]
Why not read the creds file from the same location?

**Comment by sivagms** [comment]
that didn't work. we can only do it if we host the site on a webserver.  CORS issue.
http://stackoverflow.com/questions/31269070/cors-error-when-accessing-local-json-file-using-vanilla-js-ajax-request

**Comment by SajayAntony** [comment]
The issue is that you expect it to be a `JSON` we could change or create a _creds.js file and load it using a script tag. that should be quite straight forward. 
That way setup.js can produce a js file instead of `JSON`

**Comment by sivagms** [comment]
then we should change the _creds.json format (and its parsing logic in various files). is that okay ?

**Comment by SajayAntony** [comment]
Fixed that and no index.html reads from _creds.js. 
https://github.com/SajayAntony/cmdport/blob/master/client/web/agent.js#L16
