### ISSUE TITLE
Add entry point for starting job on controller.

### ISSUE THREAD

**Issue by SajayAntony** [SajayAntony/cmdport#5]
The goal is to add a start entry point into cmdport which will send a command to the controllerTopic specified. 

### Start the contoller under topic

```
./controller.js -t mycontroller/job` --verbose
```

### Send start command to the controller. 
```
cmdport.js start -t mycontroller/job --testspec /home/controllerpath/test.md --env env.json
```

**Comment by SajayAntony** [comment]
@sivagms you need this for the actual demo.

**Comment by sivagms** [comment]
yes, I'll get that.

**Comment by sivagms** [comment]
Done. 

cmdport.js start -t mycontroller/job --testspec <test.md> --testenv <testenv.json>
