### ISSUE TITLE
Controller Environment Variables and Test Markdown format

### ISSUE THREAD

**Issue by SajayAntony** [SajayAntony/cmdport#9]
The controller needs to parse the test markdown and and send the variables to the appropriate targets. 

1. The table should be enclosed within the `<env>` tags which will not be rendered in the markdown. 
2. Additional environment variables may be passed in through an json file and the contents of it will be merged with the environment table and `$(varialble)` will be replaced with the appropriate values. 
3. Target prefix - Variables with `$(target.VARIABLE)` indicates that the variable is meant only for a specific target. 

`<env>`

| Variable | Value | Description   |  
| ---------- | ------- | ---------------- | 
| server.basepath | /home/user/performance/scripts/ | 
| client.basepath | c:\git\performance\ | 
| keep-alive | false | All targets get this value| 
| client.serverurl |  $(serverurl) |  Value passed only to the the client

`</env>`

**Comment by SajayAntony** [comment]
@sivagms This is the initial thinking of the variables sections. 
if we support something like this 

`./cmdport.js run --testspec`  `vars.md`  `test.md`  `--env env.json`

This will avoid `test.md` from becoming unncessarily complex with variable definitions.

**Comment by sivagms** [comment]
is there really a difference between vars.md and env.json ?

**Comment by SajayAntony** [comment]
The vars.md is more like the definition and env.json should be tha actual values. 
You potentially don't need vars.md since you can have an env section in test.md.

**Comment by sivagms** [comment]
yes, that's what I thought. so we'll have only two files. test.md and env.json

**Comment by sivagms** [comment]
the controller today is stateless. the incoming message has all it needs.
A problem with sending env with the setenv command and then not sending the env with every command to agent is that: the controller need to be stateful -  It needs to remember the env because it has to use it find the next machine to which it has to send the command or to replace any of the command line arguments if they are specified in the md file.  
Or probably we need to extract the machines list from the env, and send that list with every message to the agent.

**Comment by SajayAntony** [comment]
Yep that's the idea. All machines have the state setup before the tests start. For each target set target envs.

**Comment by sivagms** [comment]
the idea is clear. what I described above(that the controller should start being state full) is a consequence of implementing that idea. another consequence is to have special/wellknown env names for the set of machines.

**Comment by SajayAntony** [comment]
I'm not sure if we need to make the controller stateful. msg. env is actually merged before running the command. 
https://github.com/SajayAntony/node-red-contrib-execute/blob/master/execute.js#L50
So if you can apply the env per message as well. The point being that we might want to persist environment variables across commands and not pass it in the argument. If you can pass it in everytime then it can be picked up from the passed in env as well. 

So optiions 

```json
{"command" : "setenv" , "env" : { "id" : "runid" }}
{"command" : "printenv id" }
{"command" : "printenv id" }
{"command" : "printenv id" }
```

OR 
```json 
{"command" : "printenv id", "env" : {  "id" : "runid" }}
{"command" : "printenv id", "env" : {  "id" : "runid" }}
{"command" : "printenv id", "env" : {  "id" : "runid" }}
```

Both should have the same effect and the callback will have the original payload which in the second case should have the environment variables..
